INSERT INTO books(_id, name, translation_id) VALUES(1,'Genesis',1);
INSERT INTO books(_id, name, translation_id) VALUES(2,'Exodus',1);
INSERT INTO books(_id, name, translation_id) VALUES(3,'Leviticus',1);
INSERT INTO books(_id, name, translation_id) VALUES(4,'Numbers',1);
INSERT INTO books(_id, name, translation_id) VALUES(5,'Deuteronomy',1);
INSERT INTO books(_id, name, translation_id) VALUES(6,'Joshua',1);
INSERT INTO books(_id, name, translation_id) VALUES(7,'Judges',1);
INSERT INTO books(_id, name, translation_id) VALUES(8,'Ruth',1);
INSERT INTO books(_id, name, translation_id) VALUES(9,'First Samuel',1);
INSERT INTO books(_id, name, translation_id) VALUES(10,'Second Samuel',1);
INSERT INTO books(_id, name, translation_id) VALUES(11,'First Kings',1);
INSERT INTO books(_id, name, translation_id) VALUES(12,'Second Kings',1);
INSERT INTO books(_id, name, translation_id) VALUES(13,'First Chronicles',1);
INSERT INTO books(_id, name, translation_id) VALUES(14,'Second Chronicles',1);
INSERT INTO books(_id, name, translation_id) VALUES(15,'Ezra',1);
INSERT INTO books(_id, name, translation_id) VALUES(16,'Nehemiah',1);
INSERT INTO books(_id, name, translation_id) VALUES(17,'Esther',1);
INSERT INTO books(_id, name, translation_id) VALUES(18,'Job',1);
INSERT INTO books(_id, name, translation_id) VALUES(19,'Psalms',1);
INSERT INTO books(_id, name, translation_id) VALUES(20,'Proverbs',1);
INSERT INTO books(_id, name, translation_id) VALUES(21,'Ecclesiastes',1);
INSERT INTO books(_id, name, translation_id) VALUES(22,'Song of Songs',1);
INSERT INTO books(_id, name, translation_id) VALUES(23,'Isaiah',1);
INSERT INTO books(_id, name, translation_id) VALUES(24,'Jeremiah',1);
INSERT INTO books(_id, name, translation_id) VALUES(25,'Lamentations',1);
INSERT INTO books(_id, name, translation_id) VALUES(26,'Ezekiel',1);
INSERT INTO books(_id, name, translation_id) VALUES(27,'Daniel',1);
INSERT INTO books(_id, name, translation_id) VALUES(28,'Hosea',1);
INSERT INTO books(_id, name, translation_id) VALUES(29,'Joel',1);
INSERT INTO books(_id, name, translation_id) VALUES(30,'Amos',1);
INSERT INTO books(_id, name, translation_id) VALUES(31,'Obadiah',1);
INSERT INTO books(_id, name, translation_id) VALUES(32,'Jonah',1);
INSERT INTO books(_id, name, translation_id) VALUES(33,'Micah',1);
INSERT INTO books(_id, name, translation_id) VALUES(34,'Nahum',1);
INSERT INTO books(_id, name, translation_id) VALUES(35,'Habakkuk',1);
INSERT INTO books(_id, name, translation_id) VALUES(36,'Zephaniah',1);
INSERT INTO books(_id, name, translation_id) VALUES(37,'Haggai',1);
INSERT INTO books(_id, name, translation_id) VALUES(38,'Zechariah',1);
INSERT INTO books(_id, name, translation_id) VALUES(39,'Malachi',1);
INSERT INTO books(_id, name, translation_id) VALUES(40,'Matthew',1);
INSERT INTO books(_id, name, translation_id) VALUES(41,'Mark',1);
INSERT INTO books(_id, name, translation_id) VALUES(42,'Luke',1);
INSERT INTO books(_id, name, translation_id) VALUES(43,'John',1);
INSERT INTO books(_id, name, translation_id) VALUES(44,'Acts',1);
INSERT INTO books(_id, name, translation_id) VALUES(45,'Romans',1);
INSERT INTO books(_id, name, translation_id) VALUES(46,'First Corinthians',1);
INSERT INTO books(_id, name, translation_id) VALUES(47,'Second Corinthians',1);
INSERT INTO books(_id, name, translation_id) VALUES(48,'Galatians',1);
INSERT INTO books(_id, name, translation_id) VALUES(49,'Ephesians',1);
INSERT INTO books(_id, name, translation_id) VALUES(50,'Philippians',1);
INSERT INTO books(_id, name, translation_id) VALUES(51,'Colossians',1);
INSERT INTO books(_id, name, translation_id) VALUES(52,'First Thessalonians',1);
INSERT INTO books(_id, name, translation_id) VALUES(53,'Second Thessalonians',1);
INSERT INTO books(_id, name, translation_id) VALUES(54,'First Timothy',1);
INSERT INTO books(_id, name, translation_id) VALUES(55,'Second Timothy',1);
INSERT INTO books(_id, name, translation_id) VALUES(56,'Titus',1);
INSERT INTO books(_id, name, translation_id) VALUES(57,'Philemon',1);
INSERT INTO books(_id, name, translation_id) VALUES(58,'Hebrews',1);
INSERT INTO books(_id, name, translation_id) VALUES(59,'James',1);
INSERT INTO books(_id, name, translation_id) VALUES(60,'First Peter',1);
INSERT INTO books(_id, name, translation_id) VALUES(61,'Second Peter',1);
INSERT INTO books(_id, name, translation_id) VALUES(62,'First John',1);
INSERT INTO books(_id, name, translation_id) VALUES(63,'Second John',1);
INSERT INTO books(_id, name, translation_id) VALUES(64,'Third John',1);
INSERT INTO books(_id, name, translation_id) VALUES(65,'Jude',1);
INSERT INTO books(_id, name, translation_id) VALUES(66,'Revelation',1);
